
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.LinkedList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author crisl
 */
public class GerenciarAlmofarixado extends javax.swing.JFrame {

    DefaultTableModel tablemodel;
    LinkedList<Produto> list = new LinkedList<>();
    String user;
    CRUD crud = new CRUD();
    int index;

    /**
     * Creates new form GerenciarAlmofarixado
     */
    public GerenciarAlmofarixado() {
        initComponents();
        tablemodel = (DefaultTableModel) jTableAlmox.getModel();
        //crud.connect();
    }

    public GerenciarAlmofarixado(String user) {
        initComponents();
        tablemodel = (DefaultTableModel) jTableAlmox.getModel();
        this.user = user;
        jLabelUser.setText("USER: " + this.user);
        //crud.connect();
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabelCompany = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableAlmox = new javax.swing.JTable();
        jLabelUser = new javax.swing.JLabel();
        jButtonDelLine = new javax.swing.JButton();
        jButtonAddProduct = new javax.swing.JButton();
        jButtonEditProduct = new javax.swing.JButton();

        jButton4.setText("Salvar");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Forniture Smart - Almoxarifado");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Almoxarifado");

        jLabelCompany.setText("ViGuZot Iag-π Smurf Company");

        jTableAlmox.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CÓDIGO", "PRODUTO", "QUANTIDADE", "TIPO", "FORNECEDOR"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableAlmox);

        jLabelUser.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelUser.setText("USER: ");

        jButtonDelLine.setText("Excluir Linha");
        jButtonDelLine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDelLineActionPerformed(evt);
            }
        });

        jButtonAddProduct.setText("Adicionar Produtos");
        jButtonAddProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddProductActionPerformed(evt);
            }
        });

        jButtonEditProduct.setText("Editar Produto");
        jButtonEditProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditProductActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelCompany, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonAddProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonEditProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonDelLine, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 676, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelUser, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 512, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabelCompany))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonDelLine, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                            .addComponent(jButtonAddProduct, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                            .addComponent(jButtonEditProduct, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE))
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAddProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddProductActionPerformed
        AddProduto addP = new AddProduto(this, true);
        addP.setVisible(true);
        addTableAndList(addP.list);
    }//GEN-LAST:event_jButtonAddProductActionPerformed

    private void jButtonDelLineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDelLineActionPerformed
        try {
            int index = list.get(jTableAlmox.getSelectedRow()).getId();
            System.out.println(index);
            if (crud.deleteProduct(index) == true) {
                list.remove(jTableAlmox.getSelectedRow());
                tablemodel.removeRow(jTableAlmox.getSelectedRow());

            } else {
                JOptionPane.showMessageDialog(null, "Produto não deletado!");
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Selecione a linha do produto que deseja remover!");
        }
    }//GEN-LAST:event_jButtonDelLineActionPerformed

    private void jButtonEditProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditProductActionPerformed
        try {
            int row = jTableAlmox.getSelectedRow();
            
            UpdateProduto up = new UpdateProduto(this, true, list.get(row));
            up.setVisible(true);
            
            if (up.up == true) {
                list.remove(row);
                list.add(row, up.p);
                
                String[] new_row = new String[]{String.valueOf(up.p.getCodigo()),
                    String.valueOf(up.p.getNome()),
                    String.valueOf(up.p.getQuantidade()),
                    String.valueOf(up.p.getTipo()),
                    String.valueOf(up.p.getFornecedor())};
                
                for (int i = 0; i < new_row.length; i++) {
                    tablemodel.setValueAt(new_row[i], row, i);
                    System.out.println(new_row[i]);
                }
            } 
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Selecione a linha do produto que deseja Editar!");
        }
    }//GEN-LAST:event_jButtonEditProductActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GerenciarAlmofarixado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GerenciarAlmofarixado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GerenciarAlmofarixado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GerenciarAlmofarixado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GerenciarAlmofarixado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButtonAddProduct;
    private javax.swing.JButton jButtonDelLine;
    private javax.swing.JButton jButtonEditProduct;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelCompany;
    private javax.swing.JLabel jLabelUser;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableAlmox;
    // End of variables declaration//GEN-END:variables

    private void populateTable() {
        this.tablemodel.setNumRows(0);
        try {
            ResultSet rs = crud.getEstoque();

            while (rs.next()) {
                this.tablemodel.addRow(new String[]{rs.getString("CODIGO"),
                    rs.getString("NOME"),
                    rs.getString("QUANTIDADE"),
                    rs.getString("TIPO"),
                    rs.getString("FORNECEDOR")});
                list.add(new Produto(rs.getString("NOME"),
                        rs.getString("TIPO"),
                        Float.parseFloat(rs.getString("QUANTIDADE")),
                        Integer.parseInt(rs.getString("ID")),
                        Integer.parseInt(rs.getString("CODIGO")),
                        rs.getString("FORNECEDOR")));
            }
            this.index = list.getLast().getId();
        } catch (SQLException ex) {
            Logger.getLogger(GerenciarAlmofarixado.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void addTableAndList(LinkedList<Produto> listAdd) {
        for (int i = 0; i < listAdd.size(); i++) {
            this.tablemodel.addRow(new String[]{String.valueOf(listAdd.get(i).getCodigo()),
                String.valueOf(listAdd.get(i).getCodigo()),
                listAdd.get(i).getNome(),
                String.valueOf(listAdd.get(i).getQuantidade()),
                listAdd.get(i).getTipo(),
                listAdd.get(i).getFornecedor()});
            list.add(listAdd.get(i));
        }
        this.index += listAdd.size();
    }
}
